# Data set of people and movies they have rate 
#0 means either they havent watched it yet.

dataset={
   "Hania": {
      "Ada Apa dengan Cinta 2": 3,
      "Gundala": 5,
      "Dilan 1991": 4,
      "Bumi Manusia": 4,
      "Dua Garis Biru": 4,
      "Avengers: End Game": 0,
      "The Lion King": 0,
      "Aladdin": 0,
      "Spiderman: Far From Home": 0,
      "Captain Marvel": 0
   },
   "Topik Zulkarnain": {
      "Ada Apa dengan Cinta 2": 0,
      "Gundala": 0,
      "Dilan 1991": 0,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 5,
      "The Lion King": 5,
      "Aladdin": 0,
      "Spiderman: Far From Home": 4,
      "Captain Marvel": 2
   },
   "AhokTemanFirli": {
      "Ada Apa dengan Cinta 2": 0,
      "Gundala": 0,
      "Dilan 1991": 0,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 3,
      "The Lion King": 0,
      "Aladdin": 0,
      "Spiderman: Far From Home": 0,
      "Captain Marvel": 4
   },
   "franadek": {
      "Ada Apa dengan Cinta 2": 4,
      "Gundala": 4,
      "Dilan 1991": 4,
      "Bumi Manusia": 5,
      "Dua Garis Biru": 3,
      "Avengers: End Game": 5,
      "The Lion King": 4,
      "Aladdin": 5,
      "Spiderman: Far From Home": 4,
      "Captain Marvel": 4
   },
   "OM INDRA": {
      "Ada Apa dengan Cinta 2": 3,
      "Gundala": 0,
      "Dilan 1991": 2,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 5,
      "Avengers: End Game": 5,
      "The Lion King": 0,
      "Aladdin": 1,
      "Spiderman: Far From Home": 5,
      "Captain Marvel": 5
   },
   "Mulya": {
      "Ada Apa dengan Cinta 2": 0,
      "Gundala": 0,
      "Dilan 1991": 0,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 4,
      "The Lion King": 2,
      "Aladdin": 5,
      "Spiderman: Far From Home": 4,
      "Captain Marvel": 3
   },
   "Genjeh": {
      "Ada Apa dengan Cinta 2": 5,
      "Gundala": 4,
      "Dilan 1991": 3,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 5,
      "The Lion King": 0,
      "Aladdin": 5,
      "Spiderman: Far From Home": 4,
      "Captain Marvel": 4
   },
   "faizah": {
      "Ada Apa dengan Cinta 2": 3,
      "Gundala": 0,
      "Dilan 1991": 5,
      "Bumi Manusia": 5,
      "Dua Garis Biru": 4,
      "Avengers: End Game": 5,
      "The Lion King": 0,
      "Aladdin": 0,
      "Spiderman: Far From Home": 0,
      "Captain Marvel": 0
   },
   "Dpv": {
      "Ada Apa dengan Cinta 2": 5,
      "Gundala": 4,
      "Dilan 1991": 4,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 5,
      "The Lion King": 0,
      "Aladdin": 0,
      "Spiderman: Far From Home": 5,
      "Captain Marvel": 5
   },
   "Putrisqiana": {
      "Ada Apa dengan Cinta 2": 4,
      "Gundala": 3,
      "Dilan 1991": 2,
      "Bumi Manusia": 4,
      "Dua Garis Biru": 3,
      "Avengers: End Game": 5,
      "The Lion King": 0,
      "Aladdin": 0,
      "Spiderman: Far From Home": 4,
      "Captain Marvel": 3
   },
   "Nonton_Saat_Diskon": {
      "Ada Apa dengan Cinta 2": 4,
      "Gundala": 3,
      "Dilan 1991": 3,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 5,
      "The Lion King": 5,
      "Aladdin": 5,
      "Spiderman: Far From Home": 4,
      "Captain Marvel": 5
   },
   "Romantika": {
      "Ada Apa dengan Cinta 2": 5,
      "Gundala": 0,
      "Dilan 1991": 5,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 0,
      "The Lion King": 0,
      "Aladdin": 0,
      "Spiderman: Far From Home": 0,
      "Captain Marvel": 0
   },
   "ANI": {
      "Ada Apa dengan Cinta 2": 4,
      "Gundala": 0,
      "Dilan 1991": 4,
      "Bumi Manusia": 5,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 0,
      "The Lion King": 0,
      "Aladdin": 4,
      "Spiderman: Far From Home": 3,
      "Captain Marvel": 4
   },
   "Rima": {
      "Ada Apa dengan Cinta 2": 5,
      "Gundala": 5,
      "Dilan 1991": 5,
      "Bumi Manusia": 4,
      "Dua Garis Biru": 3,
      "Avengers: End Game": 5,
      "The Lion King": 4,
      "Aladdin": 5,
      "Spiderman: Far From Home": 5,
      "Captain Marvel": 5
   },
   "bunga": {
      "Ada Apa dengan Cinta 2": 0,
      "Gundala": 4,
      "Dilan 1991": 4,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 5,
      "The Lion King": 5,
      "Aladdin": 5,
      "Spiderman: Far From Home": 5,
      "Captain Marvel": 5
   },
   "Jawaharal": {
      "Ada Apa dengan Cinta 2": 2,
      "Gundala": 4,
      "Dilan 1991": 3,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 5,
      "Avengers: End Game": 5,
      "The Lion King": 4,
      "Aladdin": 5,
      "Spiderman: Far From Home": 5,
      "Captain Marvel": 4
   },
   "Febi ganteng gak ada obat": {
      "Ada Apa dengan Cinta 2": 4,
      "Gundala": 3,
      "Dilan 1991": 4,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 5,
      "The Lion King": 0,
      "Aladdin": 5,
      "Spiderman: Far From Home": 5,
      "Captain Marvel": 4
   },
   "Star": {
      "Ada Apa dengan Cinta 2": 4,
      "Gundala": 4,
      "Dilan 1991": 0,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 5,
      "The Lion King": 5,
      "Aladdin": 5,
      "Spiderman: Far From Home": 0,
      "Captain Marvel": 5
   },
   "Indra Junior": {
      "Ada Apa dengan Cinta 2": 4,
      "Gundala": 0,
      "Dilan 1991": 0,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 4,
      "Avengers: End Game": 5,
      "The Lion King": 5,
      "Aladdin": 5,
      "Spiderman: Far From Home": 5,
      "Captain Marvel": 5
   },
   "Indra 1991 SM": {
      "Ada Apa dengan Cinta 2": 0,
      "Gundala": 5,
      "Dilan 1991": 0,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 0,
      "The Lion King": 0,
      "Aladdin": 0,
      "Spiderman: Far From Home": 0,
      "Captain Marvel": 0
   },
   "Damar Teman Firli": {
      "Ada Apa dengan Cinta 2": 5,
      "Gundala": 0,
      "Dilan 1991": 0,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 5,
      "The Lion King": 0,
      "Aladdin": 0,
      "Spiderman: Far From Home": 5,
      "Captain Marvel": 0
   },
   "jul": {
      "Ada Apa dengan Cinta 2": 0,
      "Gundala": 3,
      "Dilan 1991": 0,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 3,
      "Avengers: End Game": 3,
      "The Lion King": 3,
      "Aladdin": 3,
      "Spiderman: Far From Home": 3,
      "Captain Marvel": 3
   },
   "luck": {
      "Ada Apa dengan Cinta 2": 3,
      "Gundala": 0,
      "Dilan 1991": 0,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 4,
      "The Lion King": 0,
      "Aladdin": 0,
      "Spiderman: Far From Home": 0,
      "Captain Marvel": 2
   },
   "Maria O.": {
      "Ada Apa dengan Cinta 2": 0,
      "Gundala": 0,
      "Dilan 1991": 0,
      "Bumi Manusia": 0,
      "Dua Garis Biru": 0,
      "Avengers: End Game": 0,
      "The Lion King": 5,
      "Aladdin": 4,
      "Spiderman: Far From Home": 0,
      "Captain Marvel": 0
   }
}